export const PRODUCTS = [
  {
    id: 1,
    name: 'Remera 1',
    description: 'Remera Hombre 1',
    price: '100',
    image: require('../../assets/images/remerasHombre/remera1.jpg'),
    category: 1,
  },
  {
    id: 2,
    name: 'Remera 2',
    description: 'Remera Deportiva Hombre 2',
    price: '200',
    image: require('../../assets/images/remerasHombre/remera2.jpg'),
    category: 1,
  },
  {
    id: 3,
    name: 'Remera 3',
    description: 'Remera Hombre 3',
    price: '300',
    image: require('../../assets/images/remerasHombre/remera3.jpeg'),
    category: 1,
  },
  {
    id: 4,
    name: 'Remera 4',
    description: 'Remera Mujer 1',
    price: '125',
    image: require('../../assets/images/remeraMujer/remera1.jpg'),
    category: 2,
  },
  {
    id: 5,
    name: 'Remera 5',
    description: 'Remera Mujer 2',
    price: '225',
    image: require('../../assets/images/remeraMujer/remera2.jpg'),
    category: 2,
  },
  {
    id: 6,
    name: 'Remera 6',
    description: 'Remera Mujer 3',
    price: '325',
    image: require('../../assets/images/remeraMujer/remera3.jpg'),
    category: 2,
  },
  {
    id: 7,
    name: 'Remera 7',
    description: 'Remera Unisex 1',
    price: '150',
    image: require('../../assets/images/remeraUnisex/remera1.jpg'),
    category: 3,
  },
  {
    id: 8,
    name: 'Remera 8',
    description: 'Remera Unisex 2',
    price: '250',
    image: require('../../assets/images/remeraUnisex/remera2.jpeg'),
    category: 3,
  },
  {
    id: 9,
    name: 'Remera 9',
    description: 'Remera Unisex 3',
    price: '350',
    image: require('../../assets/images/remeraUnisex/remera3.jpeg'),
    category: 3,
  },
  {
    id: 10,
    name: 'Remera 10',
    description: 'Remera Niño 1',
    price: '175',
    image: require('../../assets/images/remeraNinos/remera1.png'),
    category: 4,
  },
  {
    id: 11,
    name: 'Remera 11',
    description: 'Remera Niño 2',
    price: '275',
    image: require('../../assets/images/remeraNinos/remera2.jpeg'),
    category: 4,
  },
]
